### ISSUE TITLE
Windows下启动报权限错误

### ISSUE THREAD

**Issue by noahziheng** [gnulife/dphp#3]
Output:
PS D:\work\dphp> docker-compose up -d
Creating dphp_mysql_1

ERROR: for mysql  Cannot start service mysql: mkdir /d/work/dphp/volumes/mysql: permission denied
ERROR: Encountered errors while bringing up the project.

Docker for Windows 1.12.0
Windows 10 Pro
Docker Volumes共享已设置

**Comment by gnulife** [comment]
检查一下windows目录权限看看，我是在win10 pro C:\dphp下面测试的，一切正常。
